const COMMON_NAMES_ES: Record<string, string> = {
  caffeine: "Cafeína",
  aspirin: "Ácido acetilsalicílico",
  "acetylsalicylic acid": "Ácido acetilsalicílico",
  glucose: "Glucosa",
  ethanol: "Etanol",
  ibuprofeno: "Ibuprofeno",
  ibuprofen: "Ibuprofeno",
  paracetamol: "Paracetamol",
  acetaminophen: "Paracetamol",
  penicillin: "Penicilina",
  "acetic acid": "Ácido acético",
  "benzoic acid": "Ácido benzoico",
  "citric acid": "Ácido cítrico",
  "lactic acid": "Ácido láctico",
  "sulfuric acid": "Ácido sulfúrico",
  "hydrochloric acid": "Ácido clorhídrico",
  "nitric acid": "Ácido nítrico",
  "phosphoric acid": "Ácido fosfórico",
  "formic acid": "Ácido fórmico",
  "propionic acid": "Ácido propiónico",
  "butyric acid": "Ácido butírico",
  "stearic acid": "Ácido esteárico",
  "oleic acid": "Ácido oleico",
  "palmitic acid": "Ácido palmítico",
  water: "Agua",
  methane: "Metano",
  ethane: "Etano",
  propane: "Propano",
  butane: "Butano",
  pentane: "Pentano",
  hexane: "Hexano",
  heptane: "Heptano",
  octane: "Octano",
  nonane: "Nonano",
  decane: "Decano",
  ethylene: "Etileno",
  propylene: "Propileno",
  acetylene: "Acetileno",
  benzene: "Benceno",
  toluene: "Tolueno",
  xylene: "Xileno",
  phenol: "Fenol",
  aniline: "Anilina",
  glycerol: "Glicerol",
  glycerin: "Glicerina",
  methanol: "Metanol",
  "isopropyl alcohol": "Alcohol isopropílico",
  acetone: "Acetona",
  formaldehyde: "Formaldehído",
  acetaldehyde: "Acetaldehído",
  "ethyl acetate": "Acetato de etilo",
  "methyl alcohol": "Metanol",
  "ethyl alcohol": "Etanol",
  urea: "Urea",
  fructose: "Fructosa",
  sucrose: "Sacarosa",
  lactose: "Lactosa",
  maltose: "Maltosa",
  starch: "Almidón",
  cellulose: "Celulosa",
  cholesterol: "Colesterol",
  testosterone: "Testosterona",
  estrogen: "Estrógeno",
  insulin: "Insulina",
  dopamine: "Dopamina",
  serotonin: "Serotonina",
  adrenaline: "Adrenalina",
  epinephrine: "Epinefrina",
  nicotine: "Nicotina",
  "theophylline": "Teofilina",
  "theobromine": "Teobromina",
  cocaine: "Cocaína",
  morphine: "Morfina",
  "codeine": "Codeína",
  naproxen: "Naproxeno",
  diclofenac: "Diclofenaco",
  lidocaine: "Lidocaína",
  procaine: "Procaína",
  benzocaine: "Benzocaína",
  "sodium chloride": "Cloruro de sodio",
  "table salt": "Sal de mesa",
  "baking soda": "Bicarbonato de sodio",
  "sodium bicarbonate": "Bicarbonato de sodio",
  "calcium carbonate": "Carbonato de calcio",
  "iron oxide": "Óxido de hierro",
  "hydrogen peroxide": "Peróxido de hidrógeno",
  ammonia: "Amoníaco",
  ammonium: "Amonio",
  "sodium hydroxide": "Hidróxido de sodio",
  "potassium hydroxide": "Hidróxido de potasio",
  "calcium hydroxide": "Hidróxido de calcio",
  "magnesium hydroxide": "Hidróxido de magnesio",
  isopropanol: "Isopropanol",
  acetonitrile: "Acetonitrilo",
  "dimethyl sulfoxide": "Dimetil sulfóxido",
  chloroform: "Cloroformo",
  "diethyl ether": "Éter etílico",
  tetrahydrofuran: "Tetrahidrofurano",
  dichloromethane: "Diclorometano",
  "ascorbic acid": "Ácido ascórbico",
  "folic acid": "Ácido fólico",
  "salicylic acid": "Ácido salicílico",
  "linoleic acid": "Ácido linoleico",
  "arachidonic acid": "Ácido araquidónico",
  "eicosapentaenoic acid": "Ácido eicosapentaenoico",
  "docosahexaenoic acid": "Ácido docosahexaenoico",
  "vitamin c": "Vitamina C",
  "vitamin a": "Vitamina A",
  "vitamin d": "Vitamina D",
  "vitamin e": "Vitamina E",
  "vitamin b12": "Vitamina B12",
  "vitamin b6": "Vitamina B6",
  "vitamin b1": "Vitamina B1",
  riboflavin: "Riboflavina",
  niacin: "Niacina",
  biotin: "Biotina",
  "pantothenic acid": "Ácido pantoténico",
  retinol: "Retinol",
  tocopherol: "Tocoferol",
  calciferol: "Calciferol",
  phytonadione: "Fitonadiona",
};

export function getCommonNameEs(
  nameEn: string | null,
  synonyms: string[]
): string | null {
  if (!nameEn) return null;

  const lower = nameEn.toLowerCase().trim();
  if (COMMON_NAMES_ES[lower]) return COMMON_NAMES_ES[lower];

  for (const syn of synonyms) {
    const synLower = syn.toLowerCase().trim();
    if (COMMON_NAMES_ES[synLower]) return COMMON_NAMES_ES[synLower];
  }

  return null;
}
